// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gogo.proto

package gogoproto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TagCase int32

const (
	TagCase_CamelCase  TagCase = 1
	TagCase_PascalCase TagCase = 2
	TagCase_SnakeCase  TagCase = 3
)

var TagCase_name = map[int32]string{
	1: "CamelCase",
	2: "PascalCase",
	3: "SnakeCase",
}

var TagCase_value = map[string]int32{
	"CamelCase":  1,
	"PascalCase": 2,
	"SnakeCase":  3,
}

func (x TagCase) Enum() *TagCase {
	p := new(TagCase)
	*p = x
	return p
}

func (x TagCase) String() string {
	return proto.EnumName(TagCase_name, int32(x))
}

func (x *TagCase) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TagCase_value, data, "TagCase")
	if err != nil {
		return err
	}
	*x = TagCase(value)
	return nil
}

func (TagCase) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_592445b5231bc2b9, []int{0}
}

type Tag struct {
	Name                 *string  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Case                 *TagCase `protobuf:"varint,2,req,name=case,enum=gogoproto.TagCase" json:"case,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_592445b5231bc2b9, []int{0}
}
func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Tag) GetCase() TagCase {
	if m != nil && m.Case != nil {
		return *m.Case
	}
	return TagCase_CamelCase
}

var E_GoprotoEnumPrefix = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62001,
	Name:          "gogoproto.goproto_enum_prefix",
	Tag:           "varint,62001,opt,name=goproto_enum_prefix",
	Filename:      "gogo.proto",
}

var E_GoprotoEnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62021,
	Name:          "gogoproto.goproto_enum_stringer",
	Tag:           "varint,62021,opt,name=goproto_enum_stringer",
	Filename:      "gogo.proto",
}

var E_EnumStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62022,
	Name:          "gogoproto.enum_stringer",
	Tag:           "varint,62022,opt,name=enum_stringer",
	Filename:      "gogo.proto",
}

var E_EnumCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         62023,
	Name:          "gogoproto.enum_customname",
	Tag:           "bytes,62023,opt,name=enum_customname",
	Filename:      "gogo.proto",
}

var E_Enumdecl = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         62024,
	Name:          "gogoproto.enumdecl",
	Tag:           "varint,62024,opt,name=enumdecl",
	Filename:      "gogo.proto",
}

var E_EnumvalueCustomname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         66001,
	Name:          "gogoproto.enumvalue_customname",
	Tag:           "bytes,66001,opt,name=enumvalue_customname",
	Filename:      "gogo.proto",
}

var E_GoprotoGettersAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63001,
	Name:          "gogoproto.goproto_getters_all",
	Tag:           "varint,63001,opt,name=goproto_getters_all",
	Filename:      "gogo.proto",
}

var E_GoprotoEnumPrefixAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63002,
	Name:          "gogoproto.goproto_enum_prefix_all",
	Tag:           "varint,63002,opt,name=goproto_enum_prefix_all",
	Filename:      "gogo.proto",
}

var E_GoprotoStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63003,
	Name:          "gogoproto.goproto_stringer_all",
	Tag:           "varint,63003,opt,name=goproto_stringer_all",
	Filename:      "gogo.proto",
}

var E_VerboseEqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63004,
	Name:          "gogoproto.verbose_equal_all",
	Tag:           "varint,63004,opt,name=verbose_equal_all",
	Filename:      "gogo.proto",
}

var E_FaceAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63005,
	Name:          "gogoproto.face_all",
	Tag:           "varint,63005,opt,name=face_all",
	Filename:      "gogo.proto",
}

var E_GostringAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63006,
	Name:          "gogoproto.gostring_all",
	Tag:           "varint,63006,opt,name=gostring_all",
	Filename:      "gogo.proto",
}

var E_PopulateAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63007,
	Name:          "gogoproto.populate_all",
	Tag:           "varint,63007,opt,name=populate_all",
	Filename:      "gogo.proto",
}

var E_StringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63008,
	Name:          "gogoproto.stringer_all",
	Tag:           "varint,63008,opt,name=stringer_all",
	Filename:      "gogo.proto",
}

var E_OnlyoneAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63009,
	Name:          "gogoproto.onlyone_all",
	Tag:           "varint,63009,opt,name=onlyone_all",
	Filename:      "gogo.proto",
}

var E_EqualAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63013,
	Name:          "gogoproto.equal_all",
	Tag:           "varint,63013,opt,name=equal_all",
	Filename:      "gogo.proto",
}

var E_DescriptionAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63014,
	Name:          "gogoproto.description_all",
	Tag:           "varint,63014,opt,name=description_all",
	Filename:      "gogo.proto",
}

var E_TestgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63015,
	Name:          "gogoproto.testgen_all",
	Tag:           "varint,63015,opt,name=testgen_all",
	Filename:      "gogo.proto",
}

var E_BenchgenAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63016,
	Name:          "gogoproto.benchgen_all",
	Tag:           "varint,63016,opt,name=benchgen_all",
	Filename:      "gogo.proto",
}

var E_MarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63017,
	Name:          "gogoproto.marshaler_all",
	Tag:           "varint,63017,opt,name=marshaler_all",
	Filename:      "gogo.proto",
}

var E_UnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63018,
	Name:          "gogoproto.unmarshaler_all",
	Tag:           "varint,63018,opt,name=unmarshaler_all",
	Filename:      "gogo.proto",
}

var E_StableMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63019,
	Name:          "gogoproto.stable_marshaler_all",
	Tag:           "varint,63019,opt,name=stable_marshaler_all",
	Filename:      "gogo.proto",
}

var E_SizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63020,
	Name:          "gogoproto.sizer_all",
	Tag:           "varint,63020,opt,name=sizer_all",
	Filename:      "gogo.proto",
}

var E_GoprotoEnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63021,
	Name:          "gogoproto.goproto_enum_stringer_all",
	Tag:           "varint,63021,opt,name=goproto_enum_stringer_all",
	Filename:      "gogo.proto",
}

var E_EnumStringerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63022,
	Name:          "gogoproto.enum_stringer_all",
	Tag:           "varint,63022,opt,name=enum_stringer_all",
	Filename:      "gogo.proto",
}

var E_UnsafeMarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63023,
	Name:          "gogoproto.unsafe_marshaler_all",
	Tag:           "varint,63023,opt,name=unsafe_marshaler_all",
	Filename:      "gogo.proto",
}

var E_UnsafeUnmarshalerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63024,
	Name:          "gogoproto.unsafe_unmarshaler_all",
	Tag:           "varint,63024,opt,name=unsafe_unmarshaler_all",
	Filename:      "gogo.proto",
}

var E_GoprotoExtensionsMapAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63025,
	Name:          "gogoproto.goproto_extensions_map_all",
	Tag:           "varint,63025,opt,name=goproto_extensions_map_all",
	Filename:      "gogo.proto",
}

var E_GoprotoUnrecognizedAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63026,
	Name:          "gogoproto.goproto_unrecognized_all",
	Tag:           "varint,63026,opt,name=goproto_unrecognized_all",
	Filename:      "gogo.proto",
}

var E_GogoprotoImport = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63027,
	Name:          "gogoproto.gogoproto_import",
	Tag:           "varint,63027,opt,name=gogoproto_import",
	Filename:      "gogo.proto",
}

var E_ProtosizerAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63028,
	Name:          "gogoproto.protosizer_all",
	Tag:           "varint,63028,opt,name=protosizer_all",
	Filename:      "gogo.proto",
}

var E_CompareAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63029,
	Name:          "gogoproto.compare_all",
	Tag:           "varint,63029,opt,name=compare_all",
	Filename:      "gogo.proto",
}

var E_TypedeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63030,
	Name:          "gogoproto.typedecl_all",
	Tag:           "varint,63030,opt,name=typedecl_all",
	Filename:      "gogo.proto",
}

var E_EnumdeclAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63031,
	Name:          "gogoproto.enumdecl_all",
	Tag:           "varint,63031,opt,name=enumdecl_all",
	Filename:      "gogo.proto",
}

var E_GoprotoRegistration = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63032,
	Name:          "gogoproto.goproto_registration",
	Tag:           "varint,63032,opt,name=goproto_registration",
	Filename:      "gogo.proto",
}

var E_MessagenameAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63033,
	Name:          "gogoproto.messagename_all",
	Tag:           "varint,63033,opt,name=messagename_all",
	Filename:      "gogo.proto",
}

var E_GoprotoSizecacheAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63034,
	Name:          "gogoproto.goproto_sizecache_all",
	Tag:           "varint,63034,opt,name=goproto_sizecache_all",
	Filename:      "gogo.proto",
}

var E_GoprotoUnkeyedAll = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         63035,
	Name:          "gogoproto.goproto_unkeyed_all",
	Tag:           "varint,63035,opt,name=goproto_unkeyed_all",
	Filename:      "gogo.proto",
}

var E_GoprotoGetters = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64001,
	Name:          "gogoproto.goproto_getters",
	Tag:           "varint,64001,opt,name=goproto_getters",
	Filename:      "gogo.proto",
}

var E_GoprotoStringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64003,
	Name:          "gogoproto.goproto_stringer",
	Tag:           "varint,64003,opt,name=goproto_stringer",
	Filename:      "gogo.proto",
}

var E_VerboseEqual = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64004,
	Name:          "gogoproto.verbose_equal",
	Tag:           "varint,64004,opt,name=verbose_equal",
	Filename:      "gogo.proto",
}

var E_Face = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64005,
	Name:          "gogoproto.face",
	Tag:           "varint,64005,opt,name=face",
	Filename:      "gogo.proto",
}

var E_Gostring = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64006,
	Name:          "gogoproto.gostring",
	Tag:           "varint,64006,opt,name=gostring",
	Filename:      "gogo.proto",
}

var E_Populate = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64007,
	Name:          "gogoproto.populate",
	Tag:           "varint,64007,opt,name=populate",
	Filename:      "gogo.proto",
}

var E_Stringer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         67008,
	Name:          "gogoproto.stringer",
	Tag:           "varint,67008,opt,name=stringer",
	Filename:      "gogo.proto",
}

var E_Onlyone = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64009,
	Name:          "gogoproto.onlyone",
	Tag:           "varint,64009,opt,name=onlyone",
	Filename:      "gogo.proto",
}

var E_Equal = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64013,
	Name:          "gogoproto.equal",
	Tag:           "varint,64013,opt,name=equal",
	Filename:      "gogo.proto",
}

var E_Description = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64014,
	Name:          "gogoproto.description",
	Tag:           "varint,64014,opt,name=description",
	Filename:      "gogo.proto",
}

var E_Testgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64015,
	Name:          "gogoproto.testgen",
	Tag:           "varint,64015,opt,name=testgen",
	Filename:      "gogo.proto",
}

var E_Benchgen = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64016,
	Name:          "gogoproto.benchgen",
	Tag:           "varint,64016,opt,name=benchgen",
	Filename:      "gogo.proto",
}

var E_Marshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64017,
	Name:          "gogoproto.marshaler",
	Tag:           "varint,64017,opt,name=marshaler",
	Filename:      "gogo.proto",
}

var E_Unmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64018,
	Name:          "gogoproto.unmarshaler",
	Tag:           "varint,64018,opt,name=unmarshaler",
	Filename:      "gogo.proto",
}

var E_StableMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64019,
	Name:          "gogoproto.stable_marshaler",
	Tag:           "varint,64019,opt,name=stable_marshaler",
	Filename:      "gogo.proto",
}

var E_Sizer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64020,
	Name:          "gogoproto.sizer",
	Tag:           "varint,64020,opt,name=sizer",
	Filename:      "gogo.proto",
}

var E_UnsafeMarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64023,
	Name:          "gogoproto.unsafe_marshaler",
	Tag:           "varint,64023,opt,name=unsafe_marshaler",
	Filename:      "gogo.proto",
}

var E_UnsafeUnmarshaler = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64024,
	Name:          "gogoproto.unsafe_unmarshaler",
	Tag:           "varint,64024,opt,name=unsafe_unmarshaler",
	Filename:      "gogo.proto",
}

var E_GoprotoExtensionsMap = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64025,
	Name:          "gogoproto.goproto_extensions_map",
	Tag:           "varint,64025,opt,name=goproto_extensions_map",
	Filename:      "gogo.proto",
}

var E_GoprotoUnrecognized = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64026,
	Name:          "gogoproto.goproto_unrecognized",
	Tag:           "varint,64026,opt,name=goproto_unrecognized",
	Filename:      "gogo.proto",
}

var E_Protosizer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64028,
	Name:          "gogoproto.protosizer",
	Tag:           "varint,64028,opt,name=protosizer",
	Filename:      "gogo.proto",
}

var E_Compare = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64029,
	Name:          "gogoproto.compare",
	Tag:           "varint,64029,opt,name=compare",
	Filename:      "gogo.proto",
}

var E_Typedecl = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64030,
	Name:          "gogoproto.typedecl",
	Tag:           "varint,64030,opt,name=typedecl",
	Filename:      "gogo.proto",
}

var E_Messagename = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64033,
	Name:          "gogoproto.messagename",
	Tag:           "varint,64033,opt,name=messagename",
	Filename:      "gogo.proto",
}

var E_GoprotoSizecache = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64034,
	Name:          "gogoproto.goproto_sizecache",
	Tag:           "varint,64034,opt,name=goproto_sizecache",
	Filename:      "gogo.proto",
}

var E_GoprotoUnkeyed = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64035,
	Name:          "gogoproto.goproto_unkeyed",
	Tag:           "varint,64035,opt,name=goproto_unkeyed",
	Filename:      "gogo.proto",
}

var E_Tags = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: ([]*Tag)(nil),
	Field:         64036,
	Name:          "gogoproto.tags",
	Tag:           "bytes,64036,rep,name=tags",
	Filename:      "gogo.proto",
}

var E_Nullable = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65001,
	Name:          "gogoproto.nullable",
	Tag:           "varint,65001,opt,name=nullable",
	Filename:      "gogo.proto",
}

var E_Embed = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65002,
	Name:          "gogoproto.embed",
	Tag:           "varint,65002,opt,name=embed",
	Filename:      "gogo.proto",
}

var E_Customtype = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65003,
	Name:          "gogoproto.customtype",
	Tag:           "bytes,65003,opt,name=customtype",
	Filename:      "gogo.proto",
}

var E_Customname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65004,
	Name:          "gogoproto.customname",
	Tag:           "bytes,65004,opt,name=customname",
	Filename:      "gogo.proto",
}

var E_Jsontag = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65005,
	Name:          "gogoproto.jsontag",
	Tag:           "bytes,65005,opt,name=jsontag",
	Filename:      "gogo.proto",
}

var E_Moretags = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65006,
	Name:          "gogoproto.moretags",
	Tag:           "bytes,65006,opt,name=moretags",
	Filename:      "gogo.proto",
}

var E_Casttype = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65007,
	Name:          "gogoproto.casttype",
	Tag:           "bytes,65007,opt,name=casttype",
	Filename:      "gogo.proto",
}

var E_Castkey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65008,
	Name:          "gogoproto.castkey",
	Tag:           "bytes,65008,opt,name=castkey",
	Filename:      "gogo.proto",
}

var E_Castvalue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         65009,
	Name:          "gogoproto.castvalue",
	Tag:           "bytes,65009,opt,name=castvalue",
	Filename:      "gogo.proto",
}

var E_Stdtime = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65010,
	Name:          "gogoproto.stdtime",
	Tag:           "varint,65010,opt,name=stdtime",
	Filename:      "gogo.proto",
}

var E_Stdduration = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65011,
	Name:          "gogoproto.stdduration",
	Tag:           "varint,65011,opt,name=stdduration",
	Filename:      "gogo.proto",
}

var E_Wktpointer = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         65012,
	Name:          "gogoproto.wktpointer",
	Tag:           "varint,65012,opt,name=wktpointer",
	Filename:      "gogo.proto",
}

func init() {
	proto.RegisterEnum("gogoproto.TagCase", TagCase_name, TagCase_value)
	proto.RegisterType((*Tag)(nil), "gogoproto.Tag")
	proto.RegisterExtension(E_GoprotoEnumPrefix)
	proto.RegisterExtension(E_GoprotoEnumStringer)
	proto.RegisterExtension(E_EnumStringer)
	proto.RegisterExtension(E_EnumCustomname)
	proto.RegisterExtension(E_Enumdecl)
	proto.RegisterExtension(E_EnumvalueCustomname)
	proto.RegisterExtension(E_GoprotoGettersAll)
	proto.RegisterExtension(E_GoprotoEnumPrefixAll)
	proto.RegisterExtension(E_GoprotoStringerAll)
	proto.RegisterExtension(E_VerboseEqualAll)
	proto.RegisterExtension(E_FaceAll)
	proto.RegisterExtension(E_GostringAll)
	proto.RegisterExtension(E_PopulateAll)
	proto.RegisterExtension(E_StringerAll)
	proto.RegisterExtension(E_OnlyoneAll)
	proto.RegisterExtension(E_EqualAll)
	proto.RegisterExtension(E_DescriptionAll)
	proto.RegisterExtension(E_TestgenAll)
	proto.RegisterExtension(E_BenchgenAll)
	proto.RegisterExtension(E_MarshalerAll)
	proto.RegisterExtension(E_UnmarshalerAll)
	proto.RegisterExtension(E_StableMarshalerAll)
	proto.RegisterExtension(E_SizerAll)
	proto.RegisterExtension(E_GoprotoEnumStringerAll)
	proto.RegisterExtension(E_EnumStringerAll)
	proto.RegisterExtension(E_UnsafeMarshalerAll)
	proto.RegisterExtension(E_UnsafeUnmarshalerAll)
	proto.RegisterExtension(E_GoprotoExtensionsMapAll)
	proto.RegisterExtension(E_GoprotoUnrecognizedAll)
	proto.RegisterExtension(E_GogoprotoImport)
	proto.RegisterExtension(E_ProtosizerAll)
	proto.RegisterExtension(E_CompareAll)
	proto.RegisterExtension(E_TypedeclAll)
	proto.RegisterExtension(E_EnumdeclAll)
	proto.RegisterExtension(E_GoprotoRegistration)
	proto.RegisterExtension(E_MessagenameAll)
	proto.RegisterExtension(E_GoprotoSizecacheAll)
	proto.RegisterExtension(E_GoprotoUnkeyedAll)
	proto.RegisterExtension(E_GoprotoGetters)
	proto.RegisterExtension(E_GoprotoStringer)
	proto.RegisterExtension(E_VerboseEqual)
	proto.RegisterExtension(E_Face)
	proto.RegisterExtension(E_Gostring)
	proto.RegisterExtension(E_Populate)
	proto.RegisterExtension(E_Stringer)
	proto.RegisterExtension(E_Onlyone)
	proto.RegisterExtension(E_Equal)
	proto.RegisterExtension(E_Description)
	proto.RegisterExtension(E_Testgen)
	proto.RegisterExtension(E_Benchgen)
	proto.RegisterExtension(E_Marshaler)
	proto.RegisterExtension(E_Unmarshaler)
	proto.RegisterExtension(E_StableMarshaler)
	proto.RegisterExtension(E_Sizer)
	proto.RegisterExtension(E_UnsafeMarshaler)
	proto.RegisterExtension(E_UnsafeUnmarshaler)
	proto.RegisterExtension(E_GoprotoExtensionsMap)
	proto.RegisterExtension(E_GoprotoUnrecognized)
	proto.RegisterExtension(E_Protosizer)
	proto.RegisterExtension(E_Compare)
	proto.RegisterExtension(E_Typedecl)
	proto.RegisterExtension(E_Messagename)
	proto.RegisterExtension(E_GoprotoSizecache)
	proto.RegisterExtension(E_GoprotoUnkeyed)
	proto.RegisterExtension(E_Tags)
	proto.RegisterExtension(E_Nullable)
	proto.RegisterExtension(E_Embed)
	proto.RegisterExtension(E_Customtype)
	proto.RegisterExtension(E_Customname)
	proto.RegisterExtension(E_Jsontag)
	proto.RegisterExtension(E_Moretags)
	proto.RegisterExtension(E_Casttype)
	proto.RegisterExtension(E_Castkey)
	proto.RegisterExtension(E_Castvalue)
	proto.RegisterExtension(E_Stdtime)
	proto.RegisterExtension(E_Stdduration)
	proto.RegisterExtension(E_Wktpointer)
}

func init() { proto.RegisterFile("gogo.proto", fileDescriptor_592445b5231bc2b9) }

var fileDescriptor_592445b5231bc2b9 = []byte{
	// 1438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x98, 0xc9, 0x6f, 0x1c, 0x55,
	0x13, 0xc0, 0x15, 0xdb, 0x91, 0x3d, 0xe5, 0x2d, 0x1e, 0xe7, 0xcb, 0x67, 0x22, 0x10, 0x26, 0x07,
	0x64, 0x71, 0x70, 0xa4, 0x48, 0x51, 0x94, 0xb6, 0xa2, 0xc8, 0xb1, 0x1c, 0x2b, 0x88, 0x04, 0x33,
	0xb1, 0xc3, 0x76, 0x18, 0x3d, 0xf7, 0x3c, 0xb7, 0x07, 0xf7, 0x32, 0xf4, 0x12, 0xe2, 0xdc, 0x50,
	0x58, 0x84, 0x10, 0x3b, 0x12, 0x24, 0x24, 0x81, 0xb0, 0xef, 0x10, 0xf6, 0xe5, 0xc2, 0x85, 0xe5,
	0xca, 0xff, 0xc0, 0x05, 0x30, 0xbb, 0x6f, 0xbe, 0xa0, 0xea, 0xae, 0xea, 0x79, 0xd3, 0x1e, 0xf1,
	0xde, 0xdc, 0x7a, 0x66, 0xde, 0xef, 0xe7, 0xea, 0xaa, 0x7e, 0xaf, 0xca, 0x0d, 0xe0, 0x04, 0x4e,
	0x30, 0xd9, 0x08, 0x83, 0x38, 0x28, 0x97, 0xf0, 0x3a, 0xbd, 0xdc, 0x3d, 0xee, 0x04, 0x81, 0xe3,
	0xca, 0xbd, 0xe9, 0xa7, 0xa5, 0x64, 0x79, 0x6f, 0x4d, 0x46, 0x76, 0x58, 0x6f, 0xc4, 0x41, 0x98,
	0x2d, 0xde, 0x33, 0x0d, 0xdd, 0x0b, 0xc2, 0x29, 0x97, 0xa1, 0xc7, 0x17, 0x9e, 0x1c, 0xdb, 0x36,
	0xde, 0x35, 0x51, 0xaa, 0xa4, 0xd7, 0xe5, 0x1b, 0xa1, 0xc7, 0x16, 0x91, 0x1c, 0xeb, 0x1a, 0xef,
	0x9a, 0x18, 0xda, 0x57, 0x9e, 0xcc, 0xb5, 0x93, 0x0b, 0xc2, 0x99, 0x11, 0x91, 0xac, 0xa4, 0xbf,
	0xdf, 0x74, 0x00, 0x7a, 0xe9, 0x8b, 0xf2, 0x20, 0x94, 0x66, 0x84, 0x27, 0x5d, 0xfc, 0xb0, 0x63,
	0x5b, 0x79, 0x08, 0x60, 0x5e, 0x44, 0xb6, 0xc8, 0x3e, 0x77, 0xe1, 0xcf, 0x27, 0x7d, 0xb1, 0x2a,
	0xd3, 0x8f, 0xdd, 0xd6, 0x09, 0x18, 0x25, 0x63, 0x55, 0xfa, 0x89, 0x57, 0x6d, 0x84, 0x72, 0xb9,
	0x7e, 0xa6, 0x7c, 0xed, 0x64, 0x16, 0xf5, 0x24, 0x47, 0x3d, 0x39, 0xeb, 0x27, 0xde, 0xad, 0x8d,
	0xb8, 0x1e, 0xf8, 0xd1, 0xd8, 0xd5, 0x9f, 0xba, 0xc7, 0xb7, 0x4d, 0xf4, 0x55, 0x46, 0x08, 0xc5,
	0xdf, 0xe6, 0x53, 0xd0, 0xaa, 0xc0, 0xff, 0x5a, 0x7c, 0x51, 0x1c, 0xd6, 0x7d, 0x47, 0x86, 0x1a,
	0xe3, 0xb7, 0x64, 0x1c, 0x55, 0x8c, 0x27, 0x09, 0xb5, 0x66, 0x60, 0xb0, 0x13, 0xd7, 0x77, 0xe4,
	0x1a, 0x90, 0xaa, 0x64, 0x0e, 0x86, 0x53, 0x89, 0x9d, 0x44, 0x71, 0xe0, 0xa5, 0xc9, 0xfd, 0x6f,
	0xcd, 0xf7, 0xa9, 0xa6, 0x54, 0x19, 0x42, 0x6c, 0x26, 0xa7, 0x2c, 0x0b, 0xfa, 0xf0, 0x9b, 0x9a,
	0xb4, 0x5d, 0x8d, 0xe1, 0x07, 0x0a, 0x24, 0x5f, 0x6f, 0x9d, 0x82, 0x9d, 0x78, 0x7d, 0x5a, 0xb8,
	0x89, 0x54, 0x23, 0xb9, 0xa1, 0xad, 0xe7, 0x14, 0x2e, 0x63, 0xd9, 0x8f, 0xe7, 0x7a, 0xd2, 0x70,
	0x46, 0x73, 0x81, 0x12, 0x93, 0x52, 0x45, 0x47, 0xc6, 0xb1, 0x0c, 0xa3, 0xaa, 0x70, 0xdb, 0x85,
	0x77, 0xb4, 0xee, 0xe6, 0xc6, 0xf3, 0xeb, 0xad, 0x55, 0x9c, 0xcb, 0xc8, 0x69, 0xd7, 0xb5, 0x16,
	0xe1, 0xff, 0x6d, 0x9e, 0x0a, 0x03, 0xe7, 0x05, 0x72, 0xee, 0xdc, 0xf2, 0x64, 0xa0, 0x76, 0x1e,
	0xf8, 0xfb, 0xbc, 0x96, 0x06, 0xce, 0x17, 0xc8, 0x59, 0x26, 0x96, 0x4b, 0x8a, 0xc6, 0x9b, 0x61,
	0xe4, 0xb4, 0x0c, 0x97, 0x82, 0x48, 0x56, 0xe5, 0xbd, 0x89, 0x70, 0x0d, 0x74, 0x17, 0x49, 0x37,
	0x4c, 0xe0, 0x2c, 0x72, 0xe8, 0x3a, 0x08, 0x7d, 0xcb, 0xc2, 0x96, 0x06, 0x8a, 0x4b, 0xa4, 0xe8,
	0xc5, 0xf5, 0x88, 0x4e, 0xc3, 0x80, 0x13, 0x64, 0xb7, 0x64, 0x80, 0x5f, 0x26, 0xbc, 0x9f, 0x19,
	0x52, 0x34, 0x82, 0x46, 0xe2, 0x8a, 0xd8, 0x24, 0x82, 0x17, 0x59, 0xc1, 0x0c, 0x29, 0x3a, 0x48,
	0xeb, 0x4b, 0xac, 0x88, 0x94, 0x7c, 0x1e, 0x86, 0xfe, 0xc0, 0x77, 0xd7, 0x02, 0xdf, 0x24, 0x88,
	0x2b, 0x64, 0x00, 0x42, 0x50, 0x30, 0x05, 0x25, 0xd3, 0x42, 0xbc, 0xb6, 0xce, 0xdb, 0x83, 0x2b,
	0x30, 0x07, 0xc3, 0x7c, 0x38, 0xd6, 0x03, 0xdf, 0x40, 0xf1, 0x3a, 0x29, 0x86, 0x14, 0x8c, 0x6e,
	0x23, 0x96, 0x51, 0xec, 0x48, 0x13, 0xc9, 0x1b, 0x7c, 0x1b, 0x84, 0x50, 0x2a, 0x97, 0xa4, 0x6f,
	0xaf, 0x98, 0x19, 0xde, 0xe4, 0x54, 0x32, 0x83, 0x8a, 0x19, 0x18, 0xf4, 0x44, 0x18, 0xad, 0x08,
	0xd7, 0xa8, 0x1c, 0x6f, 0x91, 0x63, 0x20, 0x87, 0x28, 0x23, 0x89, 0xdf, 0x89, 0xe6, 0x6d, 0xce,
	0x88, 0x82, 0xd1, 0xd6, 0x8b, 0x62, 0xb1, 0xe4, 0xca, 0x6a, 0x27, 0xb6, 0x77, 0x78, 0xeb, 0x65,
	0xec, 0x71, 0xd5, 0x38, 0x05, 0xa5, 0xa8, 0x7e, 0xd6, 0x48, 0xf3, 0x2e, 0x57, 0x3a, 0x05, 0x10,
	0xbe, 0x13, 0xae, 0x69, 0xdb, 0x26, 0x0c, 0x64, 0xef, 0x91, 0x6c, 0x57, 0x9b, 0x56, 0x41, 0x47,
	0x42, 0xa7, 0xca, 0xf7, 0xf9, 0x48, 0x90, 0x05, 0xd7, 0x3c, 0xec, 0x4c, 0xfc, 0x48, 0x2c, 0x77,
	0x96, 0xb5, 0x0f, 0x38, 0x6b, 0x19, 0xdb, 0x92, 0xb5, 0x05, 0xd8, 0x45, 0xc6, 0xce, 0xea, 0xfa,
	0x21, 0x1f, 0xac, 0x19, 0xbd, 0xd8, 0x5a, 0xdd, 0xbb, 0x61, 0x77, 0x9e, 0xce, 0x33, 0xb1, 0xf4,
	0x23, 0x64, 0xaa, 0x9e, 0x68, 0x18, 0x98, 0xaf, 0x92, 0x99, 0x4f, 0xfc, 0xd9, 0x5c, 0x70, 0x5c,
	0x34, 0x50, 0x7e, 0x07, 0x8c, 0xb1, 0x3c, 0xf1, 0x43, 0x69, 0x07, 0x8e, 0x5f, 0x3f, 0x2b, 0x6b,
	0x06, 0xea, 0x8f, 0x0a, 0xa5, 0x5a, 0x54, 0x70, 0x34, 0x1f, 0x83, 0x1d, 0xf9, 0x40, 0x53, 0xad,
	0x7b, 0x8d, 0x20, 0x8c, 0x35, 0xc6, 0x8f, 0xb9, 0x52, 0x39, 0x77, 0x2c, 0xc5, 0xac, 0x59, 0x18,
	0x4a, 0x3f, 0x9a, 0x3e, 0x92, 0x9f, 0x90, 0x68, 0xb0, 0x49, 0xd1, 0xc1, 0x61, 0x07, 0x5e, 0x43,
	0x84, 0x26, 0xe7, 0xdf, 0xa7, 0x7c, 0x70, 0x10, 0x42, 0x07, 0x47, 0xbc, 0xd6, 0x90, 0xd8, 0xed,
	0x0d, 0x0c, 0x9f, 0xf1, 0xc1, 0xc1, 0x0c, 0x29, 0x78, 0x60, 0x30, 0x50, 0x7c, 0xce, 0x0a, 0x66,
	0x50, 0x71, 0x5b, 0xb3, 0xd1, 0x86, 0xd2, 0xa9, 0x47, 0x71, 0x28, 0x70, 0xb5, 0x46, 0xf5, 0xc5,
	0x7a, 0xeb, 0x10, 0x56, 0x51, 0x50, 0x3c, 0x89, 0x3c, 0x19, 0x45, 0xc2, 0x91, 0x38, 0x71, 0x18,
	0x04, 0xf6, 0x25, 0x9f, 0x44, 0x0a, 0x86, 0xb1, 0x29, 0x13, 0x22, 0xa6, 0xdd, 0x16, 0xf6, 0x8a,
	0x89, 0xee, 0xab, 0x42, 0x70, 0x27, 0x99, 0x45, 0xa7, 0x32, 0xff, 0x24, 0xfe, 0xaa, 0x5c, 0x33,
	0x7a, 0x3a, 0xbf, 0x2e, 0xcc, 0x3f, 0x8b, 0x19, 0x99, 0x9d, 0x21, 0xc3, 0x85, 0x79, 0xaa, 0x7c,
	0xfd, 0x16, 0xd7, 0xf1, 0xec, 0xbe, 0x58, 0x77, 0xff, 0x06, 0xdd, 0x6f, 0xeb, 0x38, 0x65, 0xdd,
	0x82, 0x0f, 0x79, 0xeb, 0xd0, 0xa3, 0x97, 0x9d, 0xdb, 0xc8, 0x9f, 0xf3, 0x96, 0x99, 0xc7, 0x3a,
	0x0a, 0x83, 0x2d, 0x03, 0x8f, 0x5e, 0xf5, 0x00, 0xa9, 0x06, 0xd4, 0x79, 0xc7, 0xda, 0x0f, 0x3d,
	0x38, 0xbc, 0xe8, 0xf1, 0x07, 0x09, 0x4f, 0x97, 0x5b, 0x87, 0xa0, 0x8f, 0x87, 0x16, 0x3d, 0xfa,
	0x10, 0xa1, 0x39, 0x82, 0x38, 0x0f, 0x2c, 0x7a, 0xfc, 0x61, 0xc6, 0x19, 0x41, 0xdc, 0x3c, 0x85,
	0xdf, 0x3c, 0xda, 0x43, 0x4d, 0x87, 0x73, 0x37, 0x05, 0xbd, 0x34, 0xa9, 0xe8, 0xe9, 0x47, 0xe8,
	0x8f, 0x33, 0x61, 0x1d, 0x80, 0xed, 0x86, 0x09, 0x7f, 0x8c, 0xd0, 0x6c, 0xbd, 0x35, 0x03, 0xfd,
	0xca, 0x74, 0xa2, 0xc7, 0x1f, 0x27, 0x5c, 0xa5, 0x30, 0x74, 0x9a, 0x4e, 0xf4, 0x82, 0x27, 0x38,
	0x74, 0x22, 0x30, 0x6d, 0x3c, 0x98, 0xe8, 0xe9, 0x27, 0x39, 0xeb, 0x8c, 0x58, 0x87, 0xa1, 0x94,
	0x37, 0x1b, 0x3d, 0xff, 0x14, 0xf1, 0x4d, 0x06, 0x33, 0xa0, 0x34, 0x3b, 0xbd, 0xe2, 0x69, 0xce,
	0x80, 0x42, 0xe1, 0x36, 0x2a, 0x0e, 0x30, 0x7a, 0xd3, 0x33, 0xbc, 0x8d, 0x0a, 0xf3, 0x0b, 0x56,
	0x33, 0x3d, 0xf3, 0xf5, 0x8a, 0x67, 0xb9, 0x9a, 0xe9, 0x7a, 0x0c, 0xa3, 0x38, 0x11, 0xe8, 0x1d,
	0xcf, 0x71, 0x18, 0x85, 0x81, 0xc0, 0x9a, 0x87, 0xf2, 0xd6, 0x69, 0x40, 0xef, 0x7b, 0x9e, 0x7c,
	0x23, 0x5b, 0x86, 0x01, 0xeb, 0x76, 0xd8, 0xd5, 0x7e, 0x12, 0xd0, 0x5b, 0xcf, 0x6f, 0x14, 0xfe,
	0x77, 0x53, 0x07, 0x01, 0x6b, 0xa1, 0xd9, 0x52, 0xd4, 0x29, 0x40, 0xaf, 0xbd, 0xb0, 0xd1, 0x7a,
	0x70, 0xab, 0x43, 0x80, 0x35, 0x0d, 0xd0, 0x6c, 0xc0, 0x7a, 0xd7, 0x45, 0x72, 0x29, 0x10, 0x6e,
	0x0d, 0xea, 0xbf, 0x7a, 0xfe, 0x12, 0x6f, 0x0d, 0x22, 0x70, 0x6b, 0x70, 0xeb, 0xd5, 0xd3, 0x97,
	0x79, 0x6b, 0x30, 0x82, 0x4f, 0xb6, 0xd2, 0xdd, 0xf4, 0x86, 0x2b, 0xfc, 0x64, 0x2b, 0x94, 0x75,
	0x02, 0x46, 0xb6, 0x34, 0x44, 0xbd, 0xea, 0x65, 0x52, 0xed, 0x28, 0xf6, 0x43, 0xb5, 0x79, 0x51,
	0x33, 0xd4, 0xdb, 0x5e, 0x29, 0x34, 0x2f, 0xea, 0x85, 0xd6, 0x2c, 0xf4, 0xc4, 0xc2, 0x31, 0xe8,
	0x7e, 0xaf, 0x6e, 0x74, 0x8f, 0x77, 0x4f, 0xf4, 0xef, 0x1b, 0x6a, 0x7d, 0x45, 0x55, 0x49, 0x71,
	0x6b, 0x0a, 0xfa, 0xfc, 0xc4, 0x75, 0x71, 0x0f, 0x96, 0xaf, 0x6b, 0xd3, 0x94, 0xa5, 0x5b, 0x63,
	0xd1, 0xcf, 0x9b, 0x94, 0x64, 0x06, 0xac, 0xfd, 0xb0, 0x5d, 0x7a, 0x4b, 0xb2, 0xa6, 0x23, 0x7f,
	0xd9, 0xe4, 0x73, 0x17, 0x57, 0x5b, 0x87, 0x01, 0xb2, 0x37, 0x2c, 0x58, 0x2d, 0x1d, 0xfb, 0xeb,
	0x66, 0xf6, 0xb2, 0x47, 0x41, 0x9a, 0x82, 0xb4, 0xb6, 0x1a, 0xc1, 0x7a, 0xab, 0x20, 0x2d, 0xec,
	0x41, 0xe8, 0xbd, 0x27, 0x0a, 0xfc, 0x58, 0x38, 0x3a, 0xfa, 0x37, 0xa2, 0x79, 0x3d, 0x26, 0xcc,
	0x0b, 0x42, 0x99, 0xe6, 0x5e, 0xc3, 0xfe, 0x4e, 0x6c, 0x0e, 0x20, 0x6c, 0x8b, 0x28, 0x36, 0xb9,
	0xef, 0x3f, 0x18, 0x66, 0x00, 0x83, 0xc6, 0xeb, 0x55, 0xb9, 0xa6, 0x63, 0xff, 0xe4, 0xa0, 0x69,
	0xbd, 0x75, 0x08, 0x4a, 0x78, 0x99, 0xbe, 0x9c, 0xd2, 0xc1, 0x7f, 0x11, 0xdc, 0x24, 0xf0, 0x2f,
	0x47, 0x71, 0x2d, 0xae, 0xeb, 0x93, 0xfd, 0x37, 0x55, 0x9a, 0xd7, 0x5b, 0xd3, 0xd0, 0x1f, 0xc5,
	0xb5, 0x5a, 0x42, 0x63, 0xae, 0x06, 0xff, 0x67, 0x33, 0x7f, 0xf3, 0x91, 0x33, 0x58, 0xed, 0xfb,
	0x56, 0xe3, 0x46, 0x50, 0xf7, 0x63, 0x19, 0xea, 0x0c, 0x1b, 0x64, 0x50, 0x90, 0x23, 0xb3, 0x30,
	0x6a, 0x07, 0x5e, 0x91, 0x3b, 0x02, 0x73, 0xc1, 0x5c, 0x30, 0x9f, 0x1e, 0x57, 0x77, 0xed, 0x71,
	0xea, 0xf1, 0x4a, 0xb2, 0x34, 0x69, 0x07, 0xde, 0x5e, 0xdc, 0x26, 0xcd, 0x77, 0xc2, 0xf9, 0xa6,
	0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x64, 0x15, 0x75, 0x46, 0x16, 0x00, 0x00,
}
